driver:
  name: vagrant

provisioner:
  name: chef_zero

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-8.6
  - name: fedora-25
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: package
  run_list:
    - recipe[test::package]
- name: source
  run_list:
    - recipe[test::source]
